### ISSUE TITLE
Question regarding Research Paper

### ISSUE THREAD

**Issue by Hazqeel09** [SunnyHaze/IML-ViT#2]
First of all, thank you for the research and sharing pretrained weight. I was reading the paper and want to ask about Table 3. For CasiaV1 why 0.5886 was bolded instead of 0.5996?

<img width="869" alt="Screenshot 2023-11-28 at 5 43 25 PM" src="https://github.com/SunnyHaze/IML-ViT/assets/33782405/e9f3eaa3-f38d-47c7-ac26-e2f5a6ac44bd">

**Comment by SunnyHaze** [comment]
Thank you for your attention to our work. 

We have carefully checked this detail and believe it is a typo. I'm sorry for the inconvenience and misleading caused by this bold. We will revise this typo in our final version. Thank you for your thoughtful reading, which helped us discover this issue.

Anyway, even though adding the multi-scale module slightly reduces the performance in CASIAv1 (homogeneous with CASIAv2 for training), we believe this signals the alleviation of overfitting. A better performance on the non-homogeneous dataset is worthwhile, which does not affect the conclusion of this section.

If you have further questions, feel free to reach out.🤗

**Comment by Hazqeel09** [comment]
Okay, thank you for your response, I just want to make sure which one is the correct one. Thank you again for your work.

**Comment by SunnyHaze** [comment]
Yep, after our checking on experiment logs, both value from each experiment is correctly positioned in their place. 

The only issue is that we should bold 0.5996 for `w/o multi-scale` instead of 0.5886 for `Full setup`.

I comment again to ensure there's no ambiguity.
